name: Integration

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_HOME_URL: ${{ secrets.REACT_APP_HOME_URL }}

    - name: Deploy
      run: |
        npm run deploy
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
